apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-01-deployment
  labels:
    app: otus-01-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-01-app
  template:
    metadata:
      labels:
        app: otus-01-app
    spec:
      containers:
        - name: otus-01
          image: eburger/otus_01:v1
          ports:
            - containerPort: 8000