apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-01-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-01-app
    template:
      metadata:
        labels:
          app: otus-01-app
      spec:
        containers:
          - name: otus-01
            image: eburger/otus-01:v1
            ports:
              - name: web
                containerPort: 8000