apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "otus-01.fullname" . }}
  labels:
  {{- include "otus-01.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingress.host}}
      http:
        paths:
          - path: /otusapp/kulikov($|/)(.*)
            backend:
              serviceName: {{ include "otus-01.fullname" . }}
              servicePort: {{ .Values.service.port }}
