apiVersion: v1
kind: Secret
metadata:
  name: otus-01-secret
type: Opaque
data:
  db-name: otus-01-db
  username: pstgrs
  password: psswrd
  connection-string: "Host=postgres;Port=5432;Database=otus-01-db;Username=pstgrs;Password=psswrd"