apiVersion: v2
name: otus-01
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: 0.3.0

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - otus-01-db
  - name: nginx-ingress-controller
    version: 5.x.x
    repository: https://charts.bitnami.com/bitnami
    tags:
      - otus-01-nginx-ingress