replicaCount: 2
jobsTtlSecondsAfterFinish: 180

image:
  repository: eburger/otus_01
  tag: v4
  pullPolicy: Always

service:
  type: NodePort
  port: 3000

metrics:
  serviceMonitor:
    enabled: true

ingress:
  host: arch.homework

postgresql:
  enabled: true
  postgresqlUsername: pstgrs
  postgresqlPassword: passwd
  postgresqlDatabase: otus-01-db
  service:
    port: "5432"

ingress-nginx:
  controller:
    kind: DaemonSet
    reportNodeInternalIp: true
    hostNetwork: false
    hostPort:
      enabled: false
      ports:
        http: 80
        https: 443
    service:
      type: NodePort
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
        namespaceSelector:
          any: true