replicaCount: 2

image:
  repository: eburger/otus-01
  tag: v2
  pullPolicy: Always

service:
  type: NodePort
  port: 3000

ingress:
  host: arch.homework

postgres:
  username: pstgrs
  password: passwd
  dbname: otus-01-db
  host: "postgres"
  port: "5432"