apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "otus-01-auth.fullname" . }}
  labels:
  {{- include "otus-01-auth.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host}}
      http:
        paths:
          - backend:
              serviceName: {{ include "otus-01-auth.fullname" . }}
              servicePort: {{ .Values.service.port }}
            path: /signin
          - backend:
              serviceName: {{ include "otus-01-auth.fullname" . }}
              servicePort: {{ .Values.service.port }}
            path: /signout
          - backend:
              serviceName: {{ include "otus-01-auth.fullname" . }}
              servicePort: {{ .Values.service.port }}
            path: /register
          - backend:
              serviceName: {{ include "otus-01-auth.fullname" . }}
              servicePort: {{ .Values.service.port }}
            path: /auth