apiVersion: batch/v1
kind: Job
metadata:
  name: otus-01-initdb
spec:
  ttlSecondsAfterFinished: 180
  template:
    metadata:
      name: otus-01-initdb
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT; 
              do echo waiting for database; sleep 2; done;
      containers:
        - name: post-install-job
          env:
            - name: POSTGRES_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: otus-01-secret
                  key: connection-string
          image: eburger/otus_01:v3
          command: ["dotnet", "SoftwareArchitect.Job.dll"]

  backoffLimit: 5