apiVersion: v1
kind: Secret
metadata:
  name: otus-01-secret
type: Opaque
data:
  db-name: b3R1cy0wMS1kYg==
  username: cHN0Z3Jz
  password: cHNzd3Jk
  connection-string: SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7RGF0YWJhc2U9b3R1cy0wMS1kYjtVc2VybmFtZT1wc3RncnM7UGFzc3dvcmQ9cHNzd3Jk