apiVersion: v2
name: otus-01
description: A Helm chart for Kubernetes

type: application
version: 0.2.0
appVersion: 0.4.0

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - otus-01-db