replicaCount: 1

image:
  repository: eburger/otus_01
  tag: v5_auth
  pullPolicy: Always

service:
  type: NodePort
  port: 3000

metrics:
  serviceMonitor:
    enabled: false

ingress:
  host: arch.homework

postgresql:
  enabled: true
  postgresqlUsername: pstgrs
  postgresqlPassword: passwd
  postgresqlDatabase: otus-01-auth-db
  service:
    port: "5432"